// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('End-to-end', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('End-to-end', async function() {
    // Test name: End-to-end
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("https://groep-5.project.ap.be/login")
    // 2 | setWindowSize | 1920x1053 | 
    await driver.manage().window().setRect(1920, 1053)
    // 3 | click | id=inputEmail | 
    await driver.findElement(By.id("inputEmail")).click()
    // 4 | type | id=inputEmail | super_admin
    await driver.findElement(By.id("inputEmail")).sendKeys("super_admin")
    // 5 | type | id=inputPassword | super_admin
    await driver.findElement(By.id("inputPassword")).sendKeys("super_admin")
    // 6 | click | css=.custom-button | 
    await driver.findElement(By.css(".custom-button")).click()
    // 7 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 8 | click | css=.MuiIconButton-colorInherit | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit")).click()
    // 9 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 10 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | mouseOut | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 12 | type | id=environmentName | environment
    await driver.findElement(By.id("environmentName")).sendKeys("environment")
    // 13 | sendKeys | id=environmentName | ${KEY_ENTER}
    await driver.findElement(By.id("environmentName")).sendKeys(Key.ENTER)
    // 14 | click | css=a:nth-child(2) p | 
    await driver.findElement(By.css("a:nth-child(2) p")).click()
    // 15 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 16 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 17 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 18 | click | css=.btn-secondary | 
    await driver.findElement(By.css(".btn-secondary")).click()
    // 19 | click | id=validityPeriod | 
    await driver.findElement(By.id("validityPeriod")).click()
    // 20 | type | id=validityPeriod | 2021-06-10
    await driver.findElement(By.id("validityPeriod")).sendKeys("2021-06-10")
    // 21 | click | css=.btn:nth-child(4) | 
    await driver.findElement(By.css(".btn:nth-child(4)")).click()
    // 22 | mouseOver | css=.btn:nth-child(4) | 
    {
      const element = await driver.findElement(By.css(".btn:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 23 | mouseOut | css=.btn:nth-child(4) | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 24 | click | css=.btn:nth-child(1) | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 25 | click | id=capabilityName | 
    await driver.findElement(By.id("capabilityName")).click()
    // 26 | type | id=capabilityName | capability 1
    await driver.findElement(By.id("capabilityName")).sendKeys("capability 1")
    // 27 | select | id=paceOfChange | label=Standard
    {
      const dropdown = await driver.findElement(By.id("paceOfChange"))
      await dropdown.findElement(By.xpath("//option[. = 'Standard']")).click()
    }
    // 28 | select | id=informationQuality | label=1
    {
      const dropdown = await driver.findElement(By.id("informationQuality"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 29 | select | id=targetOperatingModel | label=Coordination
    {
      const dropdown = await driver.findElement(By.id("targetOperatingModel"))
      await dropdown.findElement(By.xpath("//option[. = 'Coordination']")).click()
    }
    // 30 | select | id=applicationFit | label=1
    {
      const dropdown = await driver.findElement(By.id("applicationFit"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 31 | click | id=react-select-3-option-0 | 
    await driver.findElement(By.id("react-select-3-option-0")).click()
    // 32 | click | css=span:nth-child(4) | 
    await driver.findElement(By.css("span:nth-child(4)")).click()
    // 33 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 34 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 35 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 36 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 37 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 38 | click | id=capabilityName | 
    await driver.findElement(By.id("capabilityName")).click()
    // 39 | type | id=capabilityName | capability 2
    await driver.findElement(By.id("capabilityName")).sendKeys("capability 2")
    // 40 | select | id=paceOfChange | label=Standard
    {
      const dropdown = await driver.findElement(By.id("paceOfChange"))
      await dropdown.findElement(By.xpath("//option[. = 'Standard']")).click()
    }
    // 41 | select | id=informationQuality | label=1
    {
      const dropdown = await driver.findElement(By.id("informationQuality"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 42 | select | id=targetOperatingModel | label=Coordination
    {
      const dropdown = await driver.findElement(By.id("targetOperatingModel"))
      await dropdown.findElement(By.xpath("//option[. = 'Coordination']")).click()
    }
    // 43 | select | id=applicationFit | label=1
    {
      const dropdown = await driver.findElement(By.id("applicationFit"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 44 | click | css=.btn-secondary | 
    await driver.findElement(By.css(".btn-secondary")).click()
    // 45 | mouseOver | css=.btn-secondary | 
    {
      const element = await driver.findElement(By.css(".btn-secondary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 46 | mouseOut | css=.btn-secondary:nth-child(2) | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 47 | click | id=validityPeriod | 
    await driver.findElement(By.id("validityPeriod")).click()
    // 48 | type | id=validityPeriod | 2021-06-01
    await driver.findElement(By.id("validityPeriod")).sendKeys("2021-06-01")
    // 49 | click | css=.btn:nth-child(4) | 
    await driver.findElement(By.css(".btn:nth-child(4)")).click()
    // 50 | mouseOver | css=.btn:nth-child(4) | 
    {
      const element = await driver.findElement(By.css(".btn:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 51 | mouseOut | css=.btn:nth-child(4) | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 52 | click | css=.btn:nth-child(1) | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 53 | click | css=.css-1pahdxg-control > .css-1hwfws3 | 
    await driver.findElement(By.css(".css-1pahdxg-control > .css-1hwfws3")).click()
    // 54 | click | id=react-select-5-option-2 | 
    await driver.findElement(By.id("react-select-5-option-2")).click()
    // 55 | click | css=span:nth-child(4) | 
    await driver.findElement(By.css("span:nth-child(4)")).click()
    // 56 | click | id=description | 
    await driver.findElement(By.id("description")).click()
    // 57 | type | id=description | description
    await driver.findElement(By.id("description")).sendKeys("description")
    // 58 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 59 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 60 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 61 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 62 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 63 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 64 | click | id=capabilityName | 
    await driver.findElement(By.id("capabilityName")).click()
    // 65 | type | id=capabilityName | capability 3
    await driver.findElement(By.id("capabilityName")).sendKeys("capability 3")
    // 66 | select | id=paceOfChange | label=Standard
    {
      const dropdown = await driver.findElement(By.id("paceOfChange"))
      await dropdown.findElement(By.xpath("//option[. = 'Standard']")).click()
    }
    // 67 | select | id=informationQuality | label=1
    {
      const dropdown = await driver.findElement(By.id("informationQuality"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 68 | select | id=targetOperatingModel | label=Coordination
    {
      const dropdown = await driver.findElement(By.id("targetOperatingModel"))
      await dropdown.findElement(By.xpath("//option[. = 'Coordination']")).click()
    }
    // 69 | select | id=applicationFit | label=1
    {
      const dropdown = await driver.findElement(By.id("applicationFit"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 70 | click | id=react-select-7-option-2 | 
    await driver.findElement(By.id("react-select-7-option-2")).click()
    // 71 | click | css=.form-row:nth-child(4) span:nth-child(1) | 
    await driver.findElement(By.css(".form-row:nth-child(4) span:nth-child(1)")).click()
    // 72 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 73 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 74 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 75 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 76 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 77 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 78 | click | id=capabilityName | 
    await driver.findElement(By.id("capabilityName")).click()
    // 79 | type | id=capabilityName | capability 4
    await driver.findElement(By.id("capabilityName")).sendKeys("capability 4")
    // 80 | click | css=.form-row:nth-child(2) > .col-md | 
    await driver.findElement(By.css(".form-row:nth-child(2) > .col-md")).click()
    // 81 | click | css=.css-1pahdxg-control > .css-1hwfws3 | 
    await driver.findElement(By.css(".css-1pahdxg-control > .css-1hwfws3")).click()
    // 82 | click | id=react-select-8-option-0 | 
    await driver.findElement(By.id("react-select-8-option-0")).click()
    // 83 | select | id=paceOfChange | label=Standard
    {
      const dropdown = await driver.findElement(By.id("paceOfChange"))
      await dropdown.findElement(By.xpath("//option[. = 'Standard']")).click()
    }
    // 84 | select | id=informationQuality | label=1
    {
      const dropdown = await driver.findElement(By.id("informationQuality"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 85 | select | id=targetOperatingModel | label=Coordination
    {
      const dropdown = await driver.findElement(By.id("targetOperatingModel"))
      await dropdown.findElement(By.xpath("//option[. = 'Coordination']")).click()
    }
    // 86 | select | id=applicationFit | label=1
    {
      const dropdown = await driver.findElement(By.id("applicationFit"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    // 87 | click | id=react-select-9-option-0 | 
    await driver.findElement(By.id("react-select-9-option-0")).click()
    // 88 | click | css=span:nth-child(3) | 
    await driver.findElement(By.css("span:nth-child(3)")).click()
    // 89 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 90 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 91 | click | css=a:nth-child(4) > .nav__items | 
    await driver.findElement(By.css("a:nth-child(4) > .nav__items")).click()
    // 92 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 93 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 94 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 95 | click | css=.col-md | 
    await driver.findElement(By.css(".col-md")).click()
    // 96 | click | id=strategyName | 
    await driver.findElement(By.id("strategyName")).click()
    // 97 | type | id=strategyName | strategy
    await driver.findElement(By.id("strategyName")).sendKeys("strategy")
    // 98 | click | css=.css-1hwfws3 | 
    await driver.findElement(By.css(".css-1hwfws3")).click()
    // 99 | click | id=react-select-10-option-2 | 
    await driver.findElement(By.id("react-select-10-option-2")).click()
    // 100 | click | id=timeFrameStart | 
    await driver.findElement(By.id("timeFrameStart")).click()
    // 101 | type | id=timeFrameStart | 2021-06-01
    await driver.findElement(By.id("timeFrameStart")).sendKeys("2021-06-01")
    // 102 | click | id=timeFrameEnd | 
    await driver.findElement(By.id("timeFrameEnd")).click()
    // 103 | type | id=timeFrameEnd | 2021-06-24
    await driver.findElement(By.id("timeFrameEnd")).sendKeys("2021-06-24")
    // 104 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 105 | click | css=a:nth-child(5) > .nav__items | 
    await driver.findElement(By.css("a:nth-child(5) > .nav__items")).click()
    // 106 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 107 | click | css=.MuiIconButton-colorInherit | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit")).click()
    // 108 | click | id=strategyItemName | 
    await driver.findElement(By.id("strategyItemName")).click()
    // 109 | type | id=strategyItemName | strategy item
    await driver.findElement(By.id("strategyItemName")).sendKeys("strategy item")
    // 110 | select | id=strategyId | label=strategy
    {
      const dropdown = await driver.findElement(By.id("strategyId"))
      await dropdown.findElement(By.xpath("//option[. = 'strategy']")).click()
    }
    // 111 | mouseDownAt | id=strategyId | -696.5,-289
    {
      const element = await driver.findElement(By.id("strategyId"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 112 | mouseMoveAt | id=strategyId | -696.5,-289
    {
      const element = await driver.findElement(By.id("strategyId"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 113 | mouseUpAt | id=strategyId | -696.5,-289
    {
      const element = await driver.findElement(By.id("strategyId"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 114 | click | id=strategyId | 
    await driver.findElement(By.id("strategyId")).click()
    // 115 | click | id=strategyItemDescription | 
    await driver.findElement(By.id("strategyItemDescription")).click()
    // 116 | type | id=strategyItemDescription | strategy item description
    await driver.findElement(By.id("strategyItemDescription")).sendKeys("strategy item description")
    // 117 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 118 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 119 | click | css=.MuiTableRow-root:nth-child(2) .bi-chat-square | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(2) .bi-chat-square")).click()
    // 120 | click | css=.css-1hwfws3 | 
    await driver.findElement(By.css(".css-1hwfws3")).click()
    // 121 | click | id=react-select-11-option-10 | 
    await driver.findElement(By.id("react-select-11-option-10")).click()
    // 122 | select | id=strategicImportance | label=Medium
    {
      const dropdown = await driver.findElement(By.id("strategicImportance"))
      await dropdown.findElement(By.xpath("//option[. = 'Medium']")).click()
    }
    // 123 | mouseDownAt | id=strategicImportance | -727,-204
    {
      const element = await driver.findElement(By.id("strategicImportance"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 124 | mouseMoveAt | id=strategicImportance | -727,-204
    {
      const element = await driver.findElement(By.id("strategicImportance"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 125 | mouseUpAt | id=strategicImportance | -727,-204
    {
      const element = await driver.findElement(By.id("strategicImportance"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 126 | click | id=strategicImportance | 
    await driver.findElement(By.id("strategicImportance")).click()
    // 127 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 128 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 129 | mouseOut | css=.btn-primary | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 130 | click | css=.close > span:nth-child(1) | 
    await driver.findElement(By.css(".close > span:nth-child(1)")).click()
    // 131 | click | css=a:nth-child(6) p | 
    await driver.findElement(By.css("a:nth-child(6) p")).click()
    // 132 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 133 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 134 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 135 | click | css=.MuiIconButton-colorInherit | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit")).click()
    // 136 | click | id=itApplicationName | 
    await driver.findElement(By.id("itApplicationName")).click()
    // 137 | type | id=itApplicationName | it app
    await driver.findElement(By.id("itApplicationName")).sendKeys("it app")
    // 138 | type | id=version | 123
    await driver.findElement(By.id("version")).sendKeys("123")
    // 139 | click | id=purchaseDate | 
    await driver.findElement(By.id("purchaseDate")).click()
    // 140 | type | id=purchaseDate | 2021-06-01
    await driver.findElement(By.id("purchaseDate")).sendKeys("2021-06-01")
    // 141 | click | id=endOfLife | 
    await driver.findElement(By.id("endOfLife")).click()
    // 142 | type | id=endOfLife | 2021-06-25
    await driver.findElement(By.id("endOfLife")).sendKeys("2021-06-25")
    // 143 | select | id=statusId | label=2021-06-01
    {
      const dropdown = await driver.findElement(By.id("statusId"))
      await dropdown.findElement(By.xpath("//option[. = '2021-06-01']")).click()
    }
    // 144 | mouseDownAt | id=statusId | -796,-461
    {
      const element = await driver.findElement(By.id("statusId"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 145 | mouseMoveAt | id=statusId | -796,-461
    {
      const element = await driver.findElement(By.id("statusId"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 146 | mouseUpAt | id=statusId | -796,-461
    {
      const element = await driver.findElement(By.id("statusId"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 147 | click | id=statusId | 
    await driver.findElement(By.id("statusId")).click()
    // 148 | select | id=timeValue | label=INVEST
    {
      const dropdown = await driver.findElement(By.id("timeValue"))
      await dropdown.findElement(By.xpath("//option[. = 'INVEST']")).click()
    }
    // 149 | mouseDownAt | id=timeValue | -796,-547
    {
      const element = await driver.findElement(By.id("timeValue"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 150 | mouseMoveAt | id=timeValue | -796,-547
    {
      const element = await driver.findElement(By.id("timeValue"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 151 | mouseUpAt | id=timeValue | -796,-547
    {
      const element = await driver.findElement(By.id("timeValue"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 152 | click | id=timeValue | 
    await driver.findElement(By.id("timeValue")).click()
    // 153 | click | id=costCurrency | 
    await driver.findElement(By.id("costCurrency")).click()
    // 154 | type | id=costCurrency | 123
    await driver.findElement(By.id("costCurrency")).sendKeys("123")
    // 155 | type | id=currentYearlyCost | 123
    await driver.findElement(By.id("currentYearlyCost")).sendKeys("123")
    // 156 | type | id=acceptedYearlyCost | 123
    await driver.findElement(By.id("acceptedYearlyCost")).sendKeys("123")
    // 157 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 158 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 159 | mouseOut | css=.btn-primary | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 160 | click | css=.col-sm:nth-child(1) > .form-row:nth-child(1) span:nth-child(3) | 
    await driver.findElement(By.css(".col-sm:nth-child(1) > .form-row:nth-child(1) span:nth-child(3)")).click()
    // 161 | click | css=.col-sm:nth-child(2) > .form-row:nth-child(1) span:nth-child(3) | 
    await driver.findElement(By.css(".col-sm:nth-child(2) > .form-row:nth-child(1) span:nth-child(3)")).click()
    // 162 | click | css=.col-sm:nth-child(3) > .form-row:nth-child(1) span:nth-child(4) | 
    await driver.findElement(By.css(".col-sm:nth-child(3) > .form-row:nth-child(1) span:nth-child(4)")).click()
    // 163 | click | css=.col-sm:nth-child(3) > .form-row:nth-child(2) span:nth-child(3) | 
    await driver.findElement(By.css(".col-sm:nth-child(3) > .form-row:nth-child(2) span:nth-child(3)")).click()
    // 164 | click | css=.col-sm:nth-child(2) > .form-row:nth-child(2) span:nth-child(2) | 
    await driver.findElement(By.css(".col-sm:nth-child(2) > .form-row:nth-child(2) span:nth-child(2)")).click()
    // 165 | click | css=.col-sm:nth-child(1) > .form-row:nth-child(2) span:nth-child(2) | 
    await driver.findElement(By.css(".col-sm:nth-child(1) > .form-row:nth-child(2) span:nth-child(2)")).click()
    // 166 | click | css=.col-sm:nth-child(1) > .form-row:nth-child(3) span:nth-child(2) | 
    await driver.findElement(By.css(".col-sm:nth-child(1) > .form-row:nth-child(3) span:nth-child(2)")).click()
    // 167 | click | css=.col-sm:nth-child(2) > .form-row:nth-child(3) span:nth-child(5) | 
    await driver.findElement(By.css(".col-sm:nth-child(2) > .form-row:nth-child(3) span:nth-child(5)")).click()
    // 168 | click | css=.col-sm:nth-child(3) > .form-row:nth-child(3) span:nth-child(1) | 
    await driver.findElement(By.css(".col-sm:nth-child(3) > .form-row:nth-child(3) span:nth-child(1)")).click()
    // 169 | click | css=.col-sm:nth-child(3) > .form-row:nth-child(3) span:nth-child(4) | 
    await driver.findElement(By.css(".col-sm:nth-child(3) > .form-row:nth-child(3) span:nth-child(4)")).click()
    // 170 | click | css=.modal-footer > .btn | 
    await driver.findElement(By.css(".modal-footer > .btn")).click()
    // 171 | click | css=.btn-secondary:nth-child(1) | 
    await driver.findElement(By.css(".btn-secondary:nth-child(1)")).click()
    // 172 | click | css=.btn > .bi-app-indicator | 
    await driver.findElement(By.css(".btn > .bi-app-indicator")).click()
    // 173 | click | css=a:nth-child(9) p | 
    await driver.findElement(By.css("a:nth-child(9) p")).click()
    // 174 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 175 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 176 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 177 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 178 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 179 | click | id=programName | 
    await driver.findElement(By.id("programName")).click()
    // 180 | type | id=programName | JAVA
    await driver.findElement(By.id("programName")).sendKeys("JAVA")
    // 181 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 182 | click | css=a:nth-child(8) p | 
    await driver.findElement(By.css("a:nth-child(8) p")).click()
    // 183 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 184 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 185 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 186 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 187 | click | id=resourceName | 
    await driver.findElement(By.id("resourceName")).click()
    // 188 | type | id=resourceName | Resource Test
    await driver.findElement(By.id("resourceName")).sendKeys("Resource Test")
    // 189 | type | id=fullTimeEquivalentYearlyValue | 123
    await driver.findElement(By.id("fullTimeEquivalentYearlyValue")).sendKeys("123")
    // 190 | click | id=resourceDescription | 
    await driver.findElement(By.id("resourceDescription")).click()
    // 191 | type | id=resourceDescription | resource description
    await driver.findElement(By.id("resourceDescription")).sendKeys("resource description")
    // 192 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 193 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 194 | click | css=a:nth-child(10) p | 
    await driver.findElement(By.css("a:nth-child(10) p")).click()
    // 195 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 196 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 197 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 198 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 199 | click | id=businessProcessName | 
    await driver.findElement(By.id("businessProcessName")).click()
    // 200 | type | id=businessProcessName | business process
    await driver.findElement(By.id("businessProcessName")).sendKeys("business process")
    // 201 | click | id=businessProcessDescription | 
    await driver.findElement(By.id("businessProcessDescription")).click()
    // 202 | type | id=businessProcessDescription | description
    await driver.findElement(By.id("businessProcessDescription")).sendKeys("description")
    // 203 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 204 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 205 | click | css=.btn > .bi-chat-square | 
    await driver.findElement(By.css(".btn > .bi-chat-square")).click()
    // 206 | click | css=.css-1hwfws3 | 
    await driver.findElement(By.css(".css-1hwfws3")).click()
    // 207 | click | id=react-select-12-option-10 | 
    await driver.findElement(By.id("react-select-12-option-10")).click()
    // 208 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 209 | mouseOver | css=.btn-primary | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 210 | mouseOut | css=.btn-primary | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 211 | click | css=.btn-secondary | 
    await driver.findElement(By.css(".btn-secondary")).click()
    // 212 | click | css=a:nth-child(3) p | 
    await driver.findElement(By.css("a:nth-child(3) p")).click()
    // 213 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 214 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 215 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 216 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 217 | click | id=validityPeriod | 
    await driver.findElement(By.id("validityPeriod")).click()
    // 218 | click | id=validityPeriod | 
    await driver.findElement(By.id("validityPeriod")).click()
    // 219 | type | id=validityPeriod | 2021-06-17
    await driver.findElement(By.id("validityPeriod")).sendKeys("2021-06-17")
    // 220 | click | css=.jumbotron | 
    await driver.findElement(By.css(".jumbotron")).click()
    // 221 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 222 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 223 | click | css=a:nth-child(2) > .nav__items | 
    await driver.findElement(By.css("a:nth-child(2) > .nav__items")).click()
    // 224 | click | linkText=environment | 
    await driver.findElement(By.linkText("environment")).click()
    // 225 | click | css=.bi-file-earmark-pdf-fill | 
    await driver.findElement(By.css(".bi-file-earmark-pdf-fill")).click()
    // 226 | click | id=navbarDarkDropdownMenuLink | 
    await driver.findElement(By.id("navbarDarkDropdownMenuLink")).click()
    // 227 | click | css=a:nth-child(2) > .dropdown-item | 
    await driver.findElement(By.css("a:nth-child(2) > .dropdown-item")).click()
    // 228 | mouseOver | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 229 | mouseOut | css=.MuiIconButton-colorInherit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 230 | mouseOver | css=.MuiIconButton-colorInherit .material-icons | 
    {
      const element = await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 231 | click | css=.MuiIconButton-colorInherit .material-icons | 
    await driver.findElement(By.css(".MuiIconButton-colorInherit .material-icons")).click()
    // 232 | click | id=username | 
    await driver.findElement(By.id("username")).click()
    // 233 | type | id=username | sennebels@gmail.com
    await driver.findElement(By.id("username")).sendKeys("sennebels@gmail.com")
    // 234 | type | id=email | sennebels@gmail.com
    await driver.findElement(By.id("email")).sendKeys("sennebels@gmail.com")
    // 235 | select | id=roleId | label=admin
    {
      const dropdown = await driver.findElement(By.id("roleId"))
      await dropdown.findElement(By.xpath("//option[. = 'admin']")).click()
    }
    // 236 | mouseDownAt | id=roleId | -438,-461
    {
      const element = await driver.findElement(By.id("roleId"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 237 | mouseMoveAt | id=roleId | -438,-461
    {
      const element = await driver.findElement(By.id("roleId"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 238 | mouseUpAt | id=roleId | -438,-461
    {
      const element = await driver.findElement(By.id("roleId"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 239 | click | id=roleId | 
    await driver.findElement(By.id("roleId")).click()
    // 240 | click | id=username | 
    await driver.findElement(By.id("username")).click()
    // 241 | type | id=username | senne
    await driver.findElement(By.id("username")).sendKeys("senne")
    // 242 | click | css=.form-row:nth-child(1) > .form-group | 
    await driver.findElement(By.css(".form-row:nth-child(1) > .form-group")).click()
    // 243 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 244 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 245 | click | css=.bi-person-circle | 
    await driver.findElement(By.css(".bi-person-circle")).click()
    // 246 | click | css=a:nth-child(1) > .dropdown-item | 
    await driver.findElement(By.css("a:nth-child(1) > .dropdown-item")).click()
    // 247 | click | linkText=Home | 
    await driver.findElement(By.linkText("Home")).click()
    // 248 | mouseOver | linkText=Home | 
    {
      const element = await driver.findElement(By.linkText("Home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 249 | mouseOver | linkText=Home | 
    {
      const element = await driver.findElement(By.linkText("Home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 250 | mouseOut | linkText=Home | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
